/**
 * Hand-written minimal ABIs. Only what the app reads and writes — keeping this narrow means a
 * contract change that matters shows up as a type error rather than a runtime revert.
 */

export const registryAbi = [
  {
    type: "function",
    name: "activeMandates",
    inputs: [],
    outputs: [{type: "uint256[]"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mandatesOf",
    inputs: [{name: "trader", type: "address"}],
    outputs: [{type: "uint256[]"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextMandateId",
    inputs: [],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markAndEnforce",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [{type: "bool"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "markAndEnforceBatch",
    inputs: [{name: "mandateIds", type: "uint256[]"}],
    outputs: [{name: "breachedCount", type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "liveEquity",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "headroom",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [
      {name: "absolute", type: "uint256"},
      {name: "bps", type: "uint256"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "floorOf",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [
      {name: "effectiveFloor", type: "uint256"},
      {name: "lastEquity", type: "uint256"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "stateOf",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "trader", type: "address"},
          {name: "account", type: "address"},
          {name: "backer", type: "address"},
          {name: "highWaterMark", type: "uint256"},
          {name: "dayStartEquity", type: "uint256"},
          {name: "dayStartBalance", type: "uint256"},
          {name: "dayStartTime", type: "uint64"},
          {name: "lastMarkedEquity", type: "uint256"},
          {name: "lastMarkedAt", type: "uint64"},
          {name: "issuedAt", type: "uint64"},
          {name: "largestDailyGain", type: "uint256"},
          {name: "profitableDays", type: "uint32"},
          {name: "tradingDays", type: "uint32"},
          {name: "status", type: "uint8"},
          {name: "breachKind", type: "uint8"},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "termsOf",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "allocation", type: "uint256"},
          {name: "maxDrawdownBps", type: "uint16"},
          {name: "dailyLossBps", type: "uint16"},
          {name: "profitSplitBps", type: "uint16"},
          {name: "maxPositionBps", type: "uint16"},
          {name: "expiry", type: "uint64"},
          {name: "resetHourUtc", type: "uint8"},
          {name: "drawdownMode", type: "uint8"},
          {name: "maxConsistencyBps", type: "uint16"},
          {name: "minProfitableDays", type: "uint16"},
          {name: "payoutCushionBps", type: "uint16"},
          {name: "touchIsBreach", type: "bool"},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "issue",
    inputs: [
      {name: "trader", type: "address"},
      {
        name: "terms",
        type: "tuple",
        components: [
          {name: "allocation", type: "uint256"},
          {name: "maxDrawdownBps", type: "uint16"},
          {name: "dailyLossBps", type: "uint16"},
          {name: "profitSplitBps", type: "uint16"},
          {name: "maxPositionBps", type: "uint16"},
          {name: "expiry", type: "uint64"},
          {name: "resetHourUtc", type: "uint8"},
          {name: "drawdownMode", type: "uint8"},
          {name: "maxConsistencyBps", type: "uint16"},
          {name: "minProfitableDays", type: "uint16"},
          {name: "payoutCushionBps", type: "uint16"},
          {name: "touchIsBreach", type: "bool"},
        ],
      },
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recordOf",
    inputs: [{name: "trader", type: "address"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "mandatesIssued", type: "uint32"},
          {name: "mandatesSettled", type: "uint32"},
          {name: "breaches", type: "uint32"},
          {name: "profitableExits", type: "uint32"},
          {name: "daysTraded", type: "uint32"},
          {name: "capitalEntrusted", type: "uint256"},
          {name: "realisedProfit", type: "uint256"},
          {name: "realisedLoss", type: "uint256"},
          {name: "bestConsistencyBps", type: "uint16"},
          {name: "firstMandateAt", type: "uint64"},
          {name: "lastSettledAt", type: "uint64"},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payoutEligibility",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [
      {name: "ok", type: "bool"},
      {name: "reason", type: "uint8"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "consistencyScore",
    inputs: [{name: "mandateId", type: "uint256"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "EquityMarked",
    inputs: [
      {name: "mandateId", type: "uint256", indexed: true},
      {name: "equity", type: "uint256"},
      {name: "highWaterMark", type: "uint256"},
      {name: "trailingFloor", type: "uint256"},
      {name: "dailyFloor", type: "uint256"},
      {name: "netPnl", type: "int256"},
      {name: "markedAt", type: "uint64"},
      {name: "by", type: "address", indexed: true},
    ],
  },
  {
    type: "event",
    name: "Breached",
    inputs: [
      {name: "mandateId", type: "uint256", indexed: true},
      {name: "kind", type: "uint8"},
      {name: "equityAtBreach", type: "uint256"},
      {name: "floor", type: "uint256"},
      {name: "enforcedBy", type: "address", indexed: true},
    ],
  },
  {
    type: "event",
    name: "Settled",
    inputs: [
      {name: "mandateId", type: "uint256", indexed: true},
      {name: "finalStatus", type: "uint8"},
      {name: "finalEquity", type: "uint256"},
      {name: "traderPayout", type: "uint256"},
      {name: "poolReturn", type: "uint256"},
    ],
  },
] as const;

export const oracleAbi = [
  {
    type: "function",
    name: "pushPrices",
    inputs: [
      {name: "marketIds", type: "uint16[]"},
      {name: "prices", type: "uint256[]"},
      {name: "publishedAt", type: "uint64"},
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pushPrice",
    inputs: [
      {name: "marketId", type: "uint16"},
      {name: "newPrice", type: "uint256"},
      {name: "publishedAt", type: "uint64"},
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "price",
    inputs: [{name: "marketId", type: "uint16"}],
    outputs: [
      {name: "price", type: "uint256"},
      {name: "publishedAt", type: "uint64"},
    ],
    stateMutability: "view",
  },
] as const;

export const venueAbi = [
  {
    type: "function",
    name: "totalNotional",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unrealisedPnl",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "int256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openMarkets",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "uint16[]"}],
    stateMutability: "view",
  },
] as const;

export const poolAbi = [
  {type: "function", name: "totalAssets", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {type: "function", name: "idleAssets", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {
    type: "function",
    name: "totalAllocated",
    inputs: [],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pricePerShare",
    inputs: [],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
] as const;

export const accountAbi = [
  {
    type: "function",
    name: "openPosition",
    inputs: [
      {name: "marketId", type: "uint16"},
      {name: "isLong", type: "bool"},
      {name: "size", type: "uint256"},
      {name: "limitPrice", type: "uint256"},
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closePosition",
    inputs: [
      {name: "marketId", type: "uint16"},
      {name: "limitPrice", type: "uint256"},
    ],
    outputs: [{type: "int256"}],
    stateMutability: "nonpayable",
  },
  {type: "function", name: "equity", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {type: "function", name: "notional", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {type: "function", name: "trader", inputs: [], outputs: [{type: "address"}], stateMutability: "view"},
] as const;

export const venueExtraAbi = [
  {
    type: "function",
    name: "getPosition",
    inputs: [
      {name: "account", type: "address"},
      {name: "marketId", type: "uint16"},
    ],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "marketId", type: "uint16"},
          {name: "isLong", type: "bool"},
          {name: "size", type: "uint256"},
          {name: "entryPrice", type: "uint256"},
          {name: "margin", type: "uint256"},
          {name: "fundingIndexAtEntry", type: "int256"},
          {name: "openedAt", type: "uint64"},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewFill",
    inputs: [
      {name: "marketId", type: "uint16"},
      {name: "size", type: "uint256"},
      {name: "isBuy", type: "bool"},
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "freeCollateral",
    inputs: [{name: "account", type: "address"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
] as const;

export const poolExtraAbi = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      {name: "assets", type: "uint256"},
      {name: "receiver", type: "address"},
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestWithdrawal",
    inputs: [{name: "shares", type: "uint256"}],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimWithdrawal",
    inputs: [],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelWithdrawal",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "previewClaim",
    inputs: [{name: "lp", type: "address"}],
    outputs: [
      {name: "assets", type: "uint256"},
      {name: "ready", type: "bool"},
      {name: "funded", type: "bool"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{name: "", type: "address"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToAssets",
    inputs: [{name: "shares", type: "uint256"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "utilisationBps",
    inputs: [],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawalDelay",
    inputs: [],
    outputs: [{type: "uint64"}],
    stateMutability: "view",
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    inputs: [
      {name: "spender", type: "address"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [{type: "bool"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{name: "", type: "address"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      {name: "", type: "address"},
      {name: "", type: "address"},
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      {name: "to", type: "address"},
      {name: "amount", type: "uint256"},
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export const demoIssuerAbi = [
  {type: "function", name: "claim", inputs: [], outputs: [{type: "uint256"}], stateMutability: "nonpayable"},
  {
    type: "function",
    name: "claimPreset",
    inputs: [{name: "preset", type: "uint8"}],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "presetTerms",
    inputs: [{name: "preset", type: "uint8"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "allocation", type: "uint256"},
          {name: "maxDrawdownBps", type: "uint16"},
          {name: "dailyLossBps", type: "uint16"},
          {name: "profitSplitBps", type: "uint16"},
          {name: "maxPositionBps", type: "uint16"},
          {name: "expiry", type: "uint64"},
          {name: "resetHourUtc", type: "uint8"},
          {name: "drawdownMode", type: "uint8"},
          {name: "maxConsistencyBps", type: "uint16"},
          {name: "minProfitableDays", type: "uint16"},
          {name: "payoutCushionBps", type: "uint16"},
          {name: "touchIsBreach", type: "bool"},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimStatus",
    inputs: [{name: "who", type: "address"}],
    outputs: [
      {name: "claimable", type: "bool"},
      {name: "reason", type: "string"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mandateOf",
    inputs: [{name: "", type: "address"}],
    outputs: [{type: "uint256"}],
    stateMutability: "view",
  },
  {type: "function", name: "allocation", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {type: "function", name: "maxDrawdownBps", inputs: [], outputs: [{type: "uint16"}], stateMutability: "view"},
  {type: "function", name: "dailyLossBps", inputs: [], outputs: [{type: "uint16"}], stateMutability: "view"},
  {type: "function", name: "profitSplitBps", inputs: [], outputs: [{type: "uint16"}], stateMutability: "view"},
  {type: "function", name: "maxPositionBps", inputs: [], outputs: [{type: "uint16"}], stateMutability: "view"},
  {type: "function", name: "claimsMade", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
  {type: "function", name: "maxClaims", inputs: [], outputs: [{type: "uint256"}], stateMutability: "view"},
] as const;

const termsComponents = [
  {name: "allocation", type: "uint256"},
  {name: "maxDrawdownBps", type: "uint16"},
  {name: "dailyLossBps", type: "uint16"},
  {name: "profitSplitBps", type: "uint16"},
  {name: "maxPositionBps", type: "uint16"},
  {name: "expiry", type: "uint64"},
  {name: "resetHourUtc", type: "uint8"},
  {name: "drawdownMode", type: "uint8"},
  {name: "maxConsistencyBps", type: "uint16"},
  {name: "minProfitableDays", type: "uint16"},
  {name: "payoutCushionBps", type: "uint16"},
  {name: "touchIsBreach", type: "bool"},
] as const;

const criteriaComponents = [
  {name: "minMandatesSettled", type: "uint32"},
  {name: "maxBreaches", type: "uint32"},
  {name: "minProfitableExits", type: "uint32"},
  {name: "minDaysTraded", type: "uint32"},
  {name: "minRealisedProfit", type: "uint256"},
  {name: "maxConsistencyBps", type: "uint16"},
] as const;

export const bookAbi = [
  {
    type: "function",
    name: "openOffers",
    inputs: [],
    outputs: [{type: "uint256[]"}],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "offerAt",
    inputs: [{name: "offerId", type: "uint256"}],
    outputs: [
      {
        type: "tuple",
        components: [
          {name: "lp", type: "address"},
          {name: "allocation", type: "uint256"},
          {name: "slotsTotal", type: "uint32"},
          {name: "slotsTaken", type: "uint32"},
          {name: "open", type: "bool"},
          {name: "terms", type: "tuple", components: termsComponents},
          {name: "criteria", type: "tuple", components: criteriaComponents},
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "qualifies",
    inputs: [
      {name: "offerId", type: "uint256"},
      {name: "trader", type: "address"},
    ],
    outputs: [
      {name: "ok", type: "bool"},
      {name: "reason", type: "string"},
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claim",
    inputs: [{name: "offerId", type: "uint256"}],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "postOffer",
    inputs: [
      {name: "terms", type: "tuple", components: termsComponents},
      {name: "criteria", type: "tuple", components: criteriaComponents},
      {name: "slots", type: "uint32"},
    ],
    outputs: [{type: "uint256"}],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawOffer",
    inputs: [{name: "offerId", type: "uint256"}],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

/**
 * Every custom error the contracts can revert with, so viem decodes a revert by NAME instead of
 * handing back a bare selector. Pulled from the compiled ABIs; keep in sync with a rebuild.
 */
export const errorsAbi = [
  {type: "error", name: "AddressEmptyCode", inputs: [{name: "target", type: "address"}]},
  {type: "error", name: "AllocationCapExceeded", inputs: [{name: "requested", type: "uint256"}, {name: "cap", type: "uint256"}]},
  {type: "error", name: "AlreadyClaimed", inputs: [{name: "offerId", type: "uint256"}, {name: "trader", type: "address"}]},
  {type: "error", name: "AlreadyInitialised", inputs: []},
  {type: "error", name: "BpsOutOfRange", inputs: [{name: "value", type: "uint16"}]},
  {type: "error", name: "ClaimLimitReached", inputs: [{name: "limit", type: "uint256"}]},
  {type: "error", name: "ClaimsClosed", inputs: []},
  {type: "error", name: "DailyLossLooserThanDrawdown", inputs: [{name: "dailyLossBps", type: "uint16"}, {name: "maxDrawdownBps", type: "uint16"}]},
  {type: "error", name: "DrawdownMustBeNonZero", inputs: []},
  {type: "error", name: "ERC1155InsufficientBalance", inputs: [{name: "sender", type: "address"}, {name: "balance", type: "uint256"}, {name: "needed", type: "uint256"}, {name: "tokenId", type: "uint256"}]},
  {type: "error", name: "ERC1155InvalidApprover", inputs: [{name: "approver", type: "address"}]},
  {type: "error", name: "ERC1155InvalidArrayLength", inputs: [{name: "idsLength", type: "uint256"}, {name: "valuesLength", type: "uint256"}]},
  {type: "error", name: "ERC1155InvalidOperator", inputs: [{name: "operator", type: "address"}]},
  {type: "error", name: "ERC1155InvalidReceiver", inputs: [{name: "receiver", type: "address"}]},
  {type: "error", name: "ERC1155InvalidSender", inputs: [{name: "sender", type: "address"}]},
  {type: "error", name: "ERC1155MissingApprovalForAll", inputs: [{name: "operator", type: "address"}, {name: "owner", type: "address"}]},
  {type: "error", name: "ERC20InsufficientAllowance", inputs: [{name: "spender", type: "address"}, {name: "allowance", type: "uint256"}, {name: "needed", type: "uint256"}]},
  {type: "error", name: "ERC20InsufficientBalance", inputs: [{name: "sender", type: "address"}, {name: "balance", type: "uint256"}, {name: "needed", type: "uint256"}]},
  {type: "error", name: "ERC20InvalidApprover", inputs: [{name: "approver", type: "address"}]},
  {type: "error", name: "ERC20InvalidReceiver", inputs: [{name: "receiver", type: "address"}]},
  {type: "error", name: "ERC20InvalidSender", inputs: [{name: "sender", type: "address"}]},
  {type: "error", name: "ERC20InvalidSpender", inputs: [{name: "spender", type: "address"}]},
  {type: "error", name: "ERC721IncorrectOwner", inputs: [{name: "sender", type: "address"}, {name: "tokenId", type: "uint256"}, {name: "owner", type: "address"}]},
  {type: "error", name: "ERC721InsufficientApproval", inputs: [{name: "operator", type: "address"}, {name: "tokenId", type: "uint256"}]},
  {type: "error", name: "ERC721InvalidApprover", inputs: [{name: "approver", type: "address"}]},
  {type: "error", name: "ERC721InvalidOperator", inputs: [{name: "operator", type: "address"}]},
  {type: "error", name: "ERC721InvalidOwner", inputs: [{name: "owner", type: "address"}]},
  {type: "error", name: "ERC721InvalidReceiver", inputs: [{name: "receiver", type: "address"}]},
  {type: "error", name: "ERC721InvalidSender", inputs: [{name: "sender", type: "address"}]},
  {type: "error", name: "ERC721NonexistentToken", inputs: [{name: "tokenId", type: "uint256"}]},
  {type: "error", name: "ExceedsMaxRedeem", inputs: [{name: "shares", type: "uint256"}, {name: "maxShares", type: "uint256"}]},
  {type: "error", name: "ExpiryInPast", inputs: [{name: "expiry", type: "uint64"}, {name: "nowTs", type: "uint64"}]},
  {type: "error", name: "FailedCall", inputs: []},
  {type: "error", name: "FailedDeployment", inputs: []},
  {type: "error", name: "InsufficientBalance", inputs: [{name: "balance", type: "uint256"}, {name: "needed", type: "uint256"}]},
  {type: "error", name: "InsufficientIdleCapital", inputs: [{name: "requested", type: "uint256"}, {name: "idle", type: "uint256"}]},
  {type: "error", name: "InsufficientMargin", inputs: [{name: "required", type: "uint256"}, {name: "available", type: "uint256"}]},
  {type: "error", name: "InsufficientVenueLiquidity", inputs: [{name: "requested", type: "uint256"}, {name: "available", type: "uint256"}]},
  {type: "error", name: "InvalidPrice", inputs: [{name: "price", type: "int256"}]},
  {type: "error", name: "MandateExpired", inputs: [{name: "mandateId", type: "uint256"}]},
  {type: "error", name: "MandateNotActive", inputs: [{name: "mandateId", type: "uint256"}]},
  {type: "error", name: "MandateNotSettleable", inputs: [{name: "mandateId", type: "uint256"}]},
  {type: "error", name: "MarketAlreadyListed", inputs: [{name: "marketId", type: "uint16"}]},
  {type: "error", name: "MarketClosed", inputs: [{name: "marketId", type: "uint16"}]},
  {type: "error", name: "MissingPrecompile", inputs: [{name: "", type: "address"}]},
  {type: "error", name: "NoOpenPosition", inputs: [{name: "account", type: "address"}, {name: "marketId", type: "uint16"}]},
  {type: "error", name: "NoPendingWithdrawal", inputs: [{name: "owner", type: "address"}]},
  {type: "error", name: "NoPriceFeed", inputs: [{name: "marketId", type: "uint16"}]},
  {type: "error", name: "NoSlots", inputs: []},
  {type: "error", name: "NotAuthorised", inputs: [{name: "caller", type: "address"}]},
  {type: "error", name: "NotMandateTrader", inputs: [{name: "mandateId", type: "uint256"}, {name: "caller", type: "address"}]},
  {type: "error", name: "NotOfferOwner", inputs: [{name: "offerId", type: "uint256"}, {name: "caller", type: "address"}]},
  {type: "error", name: "OfferClosed", inputs: [{name: "offerId", type: "uint256"}]},
  {type: "error", name: "OfferExhausted", inputs: [{name: "offerId", type: "uint256"}]},
  {type: "error", name: "OwnableInvalidOwner", inputs: [{name: "owner", type: "address"}]},
  {type: "error", name: "OwnableUnauthorizedAccount", inputs: [{name: "account", type: "address"}]},
  {type: "error", name: "PayoutConditionNotMet", inputs: [{name: "mandateId", type: "uint256"}, {name: "reason", type: "uint8"}]},
  {type: "error", name: "PositionAlreadyOpen", inputs: [{name: "account", type: "address"}, {name: "marketId", type: "uint16"}]},
  {type: "error", name: "PositionCapExceeded", inputs: [{name: "notional", type: "uint256"}, {name: "cap", type: "uint256"}]},
  {type: "error", name: "PositionCapTooLow", inputs: [{name: "maxPositionBps", type: "uint16"}]},
  {type: "error", name: "PositionStillOpen", inputs: [{name: "mandateId", type: "uint256"}]},
  {type: "error", name: "PriceDeviationTooLarge", inputs: [{name: "previous", type: "uint256"}, {name: "next", type: "uint256"}, {name: "maxDeviationBps", type: "uint256"}]},
  {type: "error", name: "RecordDoesNotQualify", inputs: [{name: "offerId", type: "uint256"}, {name: "trader", type: "address"}, {name: "reason", type: "string"}]},
  {type: "error", name: "ReentrancyGuardReentrantCall", inputs: []},
  {type: "error", name: "SafeCastOverflowedIntDowncast", inputs: [{name: "bits", type: "uint8"}, {name: "value", type: "int256"}]},
  {type: "error", name: "SafeCastOverflowedIntToUint", inputs: [{name: "value", type: "int256"}]},
  {type: "error", name: "SafeCastOverflowedUintDowncast", inputs: [{name: "bits", type: "uint8"}, {name: "value", type: "uint256"}]},
  {type: "error", name: "SafeCastOverflowedUintToInt", inputs: [{name: "value", type: "uint256"}]},
  {type: "error", name: "SafeERC20FailedDecreaseAllowance", inputs: [{name: "spender", type: "address"}, {name: "currentAllowance", type: "uint256"}, {name: "requestedDecrease", type: "uint256"}]},
  {type: "error", name: "SafeERC20FailedOperation", inputs: [{name: "token", type: "address"}]},
  {type: "error", name: "SizeTooSmall", inputs: [{name: "size", type: "uint256"}, {name: "minSize", type: "uint256"}]},
  {type: "error", name: "SlippageExceeded", inputs: [{name: "executionPrice", type: "uint256"}, {name: "limitPrice", type: "uint256"}]},
  {type: "error", name: "SlippageToleranceTooWide", inputs: [{name: "bps", type: "uint16"}]},
  {type: "error", name: "StalePrice", inputs: [{name: "marketId", type: "uint16"}, {name: "publishedAt", type: "uint64"}, {name: "maxAge", type: "uint64"}]},
  {type: "error", name: "UnknownMandate", inputs: [{name: "mandateId", type: "uint256"}]},
  {type: "error", name: "UnknownMarket", inputs: [{name: "marketId", type: "uint16"}]},
  {type: "error", name: "WithdrawalAlreadyQueued", inputs: [{name: "owner", type: "address"}]},
  {type: "error", name: "WithdrawalNotReady", inputs: [{name: "readyAt", type: "uint64"}, {name: "nowTs", type: "uint64"}]},
  {type: "error", name: "WouldBreachFloor", inputs: [{name: "projectedEquity", type: "uint256"}, {name: "floor", type: "uint256"}]},
  {type: "error", name: "ZeroAddress", inputs: []},
  {type: "error", name: "ZeroAmount", inputs: []},
] as const;
